### ISSUE TITLE
Extended instructions?

### ISSUE THREAD

**Issue by demmm** [robrotheram/phpbb_to_flarum#3]
Hi
Could it be possible to extend the instructions for this script somewhat?
I have a phpBB forum on an old Debian server, php version is too old to be able to install flarum on this server.  So I am wondering what the settings should be (if possible) to import the phpBB database from a remote url to a local (test) install of flarum.

In particular instructions are not clear if line 12 `$servername = "localhost";` can/needs to be set to remote url, then what to set for local?  Is line 13 `$username = "user";` the phpBB db user, or the flarum user?
Or is this script only usable through phpmyadmin?
Or is it possible to export a phpBB sql database and let this script use that in the local flarum install?

**Comment by robrotheram** [comment]
Hello first thanks for your interest in this project, 
The script needs full db access to the phpbb db but not phpbb itself. One solution would be to copy the db from the old host to the new one and then run the script . I probably should update the instructions on if the old forum is on a separate host.

**Comment by demmm** [comment]
Thanks for getting back so quick.
I do have a backup.sql of the phpBB install, you mean the scipt can use that?  How to set line 12 to use that .sql file?

**Comment by robrotheram** [comment]
you will need to import the .sql file into mysql it can be the same server and configure the script to use the same server and different db. If your host can only support 1db it be a bit of a pain but the script should be able to handle the phpbb tables in the same db as flaurm (this is untested though but I see no reason why it should not work). After the import you can delete the old tables.

**Comment by demmm** [comment]
The old phpBB forum is now imported locally.
Had to do a few extra conversions, but I think I know the steps.  Once I redo this on a live server I will try to do a pull request for an updated README to set the needed steps.
I had 3 issues though with the script, but probably better to open a new issue for those.
Thanks again for getting this going.

**Comment by demmm** [comment]
Now that I have done it a few times (including Live servers), it actually is very simple and straight forward.
Use phpmyadmin (for example) on the old server with phpBB to export, download that database.
Create a new forum with a clean database on the new server, for Flarum.
Create another database on that new server, this one to import the old phpBB database into, and run the script.
Issue can be closed imo.

**Comment by robrotheram** [comment]
Thanks for letting me know how it went I will close this issue but will update the read me.
